sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=lazzurs/jenkins-agent-amazonlinux2

script:
  - docker build --pull --tag "$IMAGE_NAME" .
  - docker run "$IMAGE_NAME" cat /etc/os-release | grep -i amazon

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - export TAG=`if [ $TRAVIS_PULL_REQUEST == "false" ] && [ $TRAVIS_BRANCH == "master" ] ; then echo "latest"; else echo ${version}; fi`
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TAG}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:${TAG}"
  on:
    all_branches: true

