name: jenkins-agent-amazonlinux2

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - README.md
  schedule:
    - cron: '5 1 * * *'
  workflow_dispatch:


jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Packages Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: echo "TODAY=$(date +"%Y.%m.%d")" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1      
    - name: buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push to local registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/lazzurs/jenkins-agent-amazonlinux2:${{env.TODAY}}
    - name: build :${{env.TODAY}} image
      id: build
      run: |
        docker buildx build --platform=linux/amd64,linux/arm64 -t ghcr.io/lazzurs/jenkins-agent-amazonlinux2:${{env.TODAY}} .
    - name: publish jenkins-agent-amazonlinux2:${{env.TODAY}} image
      run: |
        docker push ghcr.io/lazzurs/jenkins-agent-amazonlinux2:${{env.TODAY}}
        docker tag ghcr.io/lazzurs/jenkins-agent-amazonlinux2:${{env.TODAY}} ghcr.io/lazzurs/jenkins-agent-amazonlinux2:latest
        docker push ghcr.io/lazzurs/jenkins-agent-amazonlinux2:latest
